name: Unit Tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]



jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: build and run unit tests
      run: |
        mkdir build && cd build
        cmake ..
        make build-tests
        for t in $(ls test); do test/$t; done