name: Unit Tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: build and run unit tests
        run: |
          mkdir build && cd build
          cmake ..
          make gor_test utils_test
          ./test/gor_test
          ./test/utils_test